openapi: 3.0.0
info:
  title: Jumna
  version: 1.0.0
  description: 'Node.js application with typescript,javascript'
servers:
  - url: 'http://localhost:5000/api'
    description: API to get User ID
tags:
  - name: Users
    description: Secured Admin Calls
paths:
  /users/{id}:
    get:
      tags:
        - Users
      summary: Get details of a user
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: User ID
      responses:
        '200':
          description: Success
          content:
            application/json: 
              schema:
                allOf:
                  - $ref: '#/components/schemas/Success'
        '400':
          description: 'User not found in the records'
          content:
            application/json:
              schema:
                allOf:
                  - $ref:#/definitions/BadRequest'

definitions:
  BadRequest:
    description: Bad Request
    content:
      application/json:
        schema:
          allOf:
            - $ref: '#/components/schemas/Error'
components:
  securitySchemes:
    admintoken:
      type: http
      scheme: bearer
      bearerFormat: JWT
    token:
      type: http
      scheme: bearer
      bearerFormat: JWT
    merchant_token:
      type: http
      scheme: bearer
      in: header
      name: token
    aisle_token:
      type: http
      scheme: bearer
      in: header
      name: token
  schemas:
    Error:
      description: Fail
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              error:
                type: string
    Success:
      description: Success
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        email:
          type: string
