export const USER_LOGIN_PROGRESS = "USER_LOGIN_PROGRESS";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const FETCH_USERS_PROGRESS = "FETCH_USERS_PROGRESS";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
