export const PATIENT_PAGINATED_LIST_PROGRESS = "PATIENT_PAGINATED_LIST_PROGRESS";
export const PATIENT_PAGINATED_LIST_SUCCESS = "PATIENT_PAGINATED_LIST_SUCCESS";
export const ADD_PATIENT_PROGRESS = "ADD_PATIENT_PROGRESS";
export const ADD_PATIENT_SUCCESS = "ADD_PATIENT_SUCCESS";
